# Generated by Django 2.1.3 on 2018-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20181118_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default=1, help_text='Nome da empresa', max_length=100),
            preserve_default=False,
        ),
    ]
